/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.saloonproject.telas;

import br.com.saloonproject.dal.ModuloConexao;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Carlos
 */
public class TelaNovoServico extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaNovoServico
     */
    public TelaNovoServico() {
        initComponents();
        conexao = ModuloConexao.conect();
    }

    private void adicionar() {
        String sql = "insert into tbservico(nmservico,compercent) values(?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtServNome.getText());
            pst.setString(2, txtServComissao.getText());
            if ((txtServNome.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
            } else {

                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Servico adicionado com sucesso.");
                    limpar();
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    private void pesquisar_servico() {
        String sql = "select matservico as Matricula, nmservico as Nome, compercent as Percentual_Comissao from tbservico where nmservico like ?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtBuscaServico.getText() + "%");
            rs = pst.executeQuery();
            tblServicos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void setar_campos() {
        int setar = tblServicos.getSelectedRow();
        txtServMat.setText(tblServicos.getModel().getValueAt(setar, 0).toString());
        txtServNome.setText(tblServicos.getModel().getValueAt(setar, 1).toString());
        txtServComissao.setText(tblServicos.getModel().getValueAt(setar, 2).toString());
        btAddServ.setEnabled(false);

    }

    private void alterar() {
        String sql = "update tbservico set nmservico=?,compercent=? where matservico=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtServNome.getText());
            pst.setString(2, txtServComissao.getText());
            pst.setString(3, txtServMat.getText());

            if ((txtServNome.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
            } else {

                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Dados alterados com sucesso.");
                    limpar();
                    btAddServ.setEnabled(true);
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    public void deletar() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover o serviço?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from tbservico where matservico=?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtServMat.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Dados deletados com sucesso.");
                    limpar();
                    btAddServ.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível remover ou encontrar o usário.");
                    limpar();
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }

    }

    private void limpar() {
        txtServMat.setText(null);
        txtServNome.setText(null);
        txtServComissao.setText(null);
        ((DefaultTableModel) tblServicos.getModel()).setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btAddServ = new javax.swing.JButton();
        btDelServ = new javax.swing.JButton();
        btEditServ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtServNome = new javax.swing.JTextField();
        txtBuscaServico = new javax.swing.JTextField();
        txtServComissao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtServMat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Novo Servico");
        setPreferredSize(new java.awt.Dimension(720, 630));

        jLabel5.setText("Comissão (%)");

        btAddServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/addicon.png"))); // NOI18N
        btAddServ.setToolTipText("Adicionar");
        btAddServ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAddServ.setPreferredSize(new java.awt.Dimension(80, 80));
        btAddServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddServActionPerformed(evt);
            }
        });

        btDelServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/deleticon.png"))); // NOI18N
        btDelServ.setToolTipText("Excluir");
        btDelServ.setMaximumSize(new java.awt.Dimension(54, 54));
        btDelServ.setMinimumSize(new java.awt.Dimension(54, 54));
        btDelServ.setPreferredSize(new java.awt.Dimension(80, 80));
        btDelServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelServActionPerformed(evt);
            }
        });

        btEditServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editicon.png"))); // NOI18N
        btEditServ.setToolTipText("Editar Dados");
        btEditServ.setPreferredSize(new java.awt.Dimension(80, 80));
        btEditServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditServActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/searchIcon.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtBuscaServico.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtBuscaServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaServicoKeyReleased(evt);
            }
        });

        tblServicos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricula", "Nome Servico", "Comissão (%)"
            }
        ));
        tblServicos.setFocusable(false);
        tblServicos.getTableHeader().setReorderingAllowed(false);
        tblServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicos);

        jLabel7.setText("* (Campos Obrigatórios)");

        jLabel2.setText("* Nome");

        txtServMat.setEnabled(false);

        jLabel4.setText("* Mat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(344, 344, 344))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(btAddServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btDelServ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btEditServ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtServNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtServComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtServMat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtServComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btAddServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDelServ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btEditServ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        setBounds(0, 0, 720, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddServActionPerformed
        adicionar();
    }//GEN-LAST:event_btAddServActionPerformed

    private void btDelServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelServActionPerformed
        deletar();
    }//GEN-LAST:event_btDelServActionPerformed

    private void btEditServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditServActionPerformed
        alterar();
    }//GEN-LAST:event_btEditServActionPerformed

    private void txtBuscaServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaServicoKeyReleased
        pesquisar_servico();        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaServicoKeyReleased

    private void tblServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicosMouseClicked
        setar_campos();        // TODO add your handling code here:
    }//GEN-LAST:event_tblServicosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddServ;
    private javax.swing.JButton btDelServ;
    private javax.swing.JButton btEditServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtBuscaServico;
    private javax.swing.JTextField txtServComissao;
    private javax.swing.JTextField txtServMat;
    private javax.swing.JTextField txtServNome;
    // End of variables declaration//GEN-END:variables
}
